/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type AudioFile = string;
export type Start = number;
export type End = number;
export type SpeakerId = string | null;
export type TranscriptText = string | null;
export type Lang = string | null;
export type DialectProbs = {
  [k: string]: number;
} | null;
export type AlignmentConfidence = number | null;
export type DiarizationConfidence = number | null;

export interface AudioSegment {
  audio_file: AudioFile;
  start: Start;
  end: End;
  speaker_id?: SpeakerId;
  transcript_text?: TranscriptText;
  lang?: Lang;
  dialect_probs?: DialectProbs;
  alignment_confidence?: AlignmentConfidence;
  diarization_confidence?: DiarizationConfidence;
  [k: string]: unknown;
}
