/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type MinMinutes90 = number;
export type PhonemeCoverage = number;
export type TargetDialectMix = {
  [k: string]: number;
} | null;

export interface CurationTargets {
  min_minutes_90?: MinMinutes90;
  phoneme_coverage?: PhonemeCoverage;
  target_dialect_mix?: TargetDialectMix;
  [k: string]: unknown;
}
