/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Word = string;
export type Ipa = string;
export type Dialect = string | null;
export type Notes = string | null;

export interface G2POverride {
  word: Word;
  ipa: Ipa;
  dialect?: Dialect;
  notes?: Notes;
  [k: string]: unknown;
}
