/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Pattern = string;
export type Ipa = string;
export type Conditions = {
  [k: string]: string;
} | null;
export type Priority = number;

export interface G2PRule {
  pattern: Pattern;
  ipa: Ipa;
  conditions?: Conditions;
  priority?: Priority;
  [k: string]: unknown;
}
