/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Language = string;
export type Dialect = string;
export type Script = string;
export type Version = string;
export type UpdatedAt = string | null;
export type PhonemeInventory = string[];
export type Pattern = string;
export type Ipa = string;
export type Conditions = {
  [k: string]: string;
} | null;
export type Priority = number;
export type G2PRules = G2PRule[];
export type Word = string;
export type Ipa1 = string;
export type Dialect1 = string | null;
export type Notes = string | null;
export type G2POverrides = G2POverride[];
export type LexiconRefs = string[];
export type StyleTokens = string[];
export type EmotionTokens = string[];
export type SpeakingRate = number;
export type PitchBias = number;
export type PauseBias = number;
export type FillerBias = number;
export type FallbackChain = string[];
export type MinMinutes90 = number;
export type PhonemeCoverage = number;
export type TargetDialectMix = {
  [k: string]: number;
} | null;
export type TtsStrategy = "standalone" | "grouped" | "cloud_fallback";

export interface LanguageProfileV1 {
  language: Language;
  dialect: Dialect;
  script: Script;
  version?: Version;
  updated_at?: UpdatedAt;
  phoneme_inventory: PhonemeInventory;
  g2p_rules?: G2PRules;
  g2p_overrides?: G2POverrides;
  lexicon_refs?: LexiconRefs;
  register_defaults?: RegisterDefaults;
  style_tokens?: StyleTokens;
  emotion_tokens?: EmotionTokens;
  tts_defaults?: TTSDefaults;
  fallback_chain?: FallbackChain;
  curation_targets?: CurationTargets;
  tts_strategy?: TtsStrategy;
  [k: string]: unknown;
}
export interface G2PRule {
  pattern: Pattern;
  ipa: Ipa;
  conditions?: Conditions;
  priority?: Priority;
  [k: string]: unknown;
}
export interface G2POverride {
  word: Word;
  ipa: Ipa1;
  dialect?: Dialect1;
  notes?: Notes;
  [k: string]: unknown;
}
export interface RegisterDefaults {
  [k: string]: number;
}
export interface TTSDefaults {
  speaking_rate?: SpeakingRate;
  pitch_bias?: PitchBias;
  pause_bias?: PauseBias;
  filler_bias?: FillerBias;
  [k: string]: unknown;
}
export interface CurationTargets {
  min_minutes_90?: MinMinutes90;
  phoneme_coverage?: PhonemeCoverage;
  target_dialect_mix?: TargetDialectMix;
  [k: string]: unknown;
}
