/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Clarity = number;
export type Alignment = number;
export type Diarization = number;
export type TranscriptAccuracy = number;
export type Validity = number;
export type Shape = number;
export type Total = number;
export type EligibleLearner = boolean;
export type EligibleTraining = boolean;
export type Notes = string | null;

export interface SegmentScore {
  clarity: Clarity;
  alignment: Alignment;
  diarization: Diarization;
  transcript_accuracy: TranscriptAccuracy;
  validity: Validity;
  shape: Shape;
  total: Total;
  eligible_learner: EligibleLearner;
  eligible_training: EligibleTraining;
  notes?: Notes;
  [k: string]: unknown;
}
