/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type DocId = string;
export type Start = number;
export type End = number;

export interface SourceRef {
  doc_id: DocId;
  start: Start;
  end: End;
  [k: string]: unknown;
}
