/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Text = string;
export type Lang = string;
export type IsDialogue = boolean;
export type Topic = string | null;
export type RegisterType = string | null;
export type CodeSwitchSpans = [unknown, unknown][];
export type DocId = string;
export type Start = number;
export type End = number;

export interface TextSegment {
  text: Text;
  lang: Lang;
  labels: Labels;
  source_ref: SourceRef;
  [k: string]: unknown;
}
export interface Labels {
  is_dialogue: IsDialogue;
  topic?: Topic;
  register_type?: RegisterType;
  code_switch_spans?: CodeSwitchSpans;
  [k: string]: unknown;
}
export interface SourceRef {
  doc_id: DocId;
  start: Start;
  end: End;
  [k: string]: unknown;
}
