/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SpeakingRate = number;
export type PitchBias = number;
export type PauseBias = number;
export type FillerBias = number;

export interface TTSDefaults {
  speaking_rate?: SpeakingRate;
  pitch_bias?: PitchBias;
  pause_bias?: PauseBias;
  filler_bias?: FillerBias;
  [k: string]: unknown;
}
