[project]
name = "mumbl_dataset_builder"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
  "pydantic>=2.6,<3",
  "psycopg[binary]>=3.1",
]

[project.scripts]
dataset-build = "mumbl_dataset_builder.tools.dataset_build:main"

[tool.setuptools.packages.find]
where = ["src"]
